SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `donor_system` DEFAULT CHARACTER SET utf8 ;
USE `donor_system` ;

CREATE TABLE IF NOT EXISTS `donor_system`.`donors` (
  `donorId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45),
  `email` VARCHAR(45),
  `password` VARCHAR(45),
  `phoneNumber` VARCHAR(10),
  `status` VARCHAR(45),
  `bloodGroup` VARCHAR(2),
  PRIMARY KEY (`donorId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `donor_system`.`patients` (
  `patientId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45),
  `email` VARCHAR(45),
  `password` VARCHAR(45),
  `diagnose` VARCHAR(45),
  `bloodGroup` VARCHAR(2),
  `phoneNumber` VARCHAR(10),
  PRIMARY KEY (`patientId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `donor_system`.`websites` (
  `websiteId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45),
  `description` VARCHAR(200),
  PRIMARY KEY (`websiteId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;